apiVersion: v1
kind: Service
metadata:
  name: hello-SimpleTime-service
  labels:
    app: hello-SimpleTimeService
spec: 
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: hello-SimpleTimeService
